apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword
            - name: MYSQL_DATABASE
              value: login_db
          volumeMounts:
            - name: db-volume
              mountPath: /docker-entrypoint-initdb.d
              subPath: db.sql
      volumes:
        - name: db-volume
          configMap:
            name: db-sql

