version: "3.8"

services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=login_db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: login_db
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

